[misc]
# ~/.config/topgrade.toml - Configuration for the Topgrade system updater

# --- Disable Specific Steps ---

# Disable steps by adding their names to this list.
# I disabled 'uv' because it's installed via Homebrew and updating it via
# `uv self update` (which Topgrade tries by default) fails for managed installations.
# Homebrew will handle updating uv correctly during its step.
disable = ["uv"]

# --- Git Repositories (Example - Currently Disabled) ---
# Automatically pull updates for specified local Git repositories.

# Uncomment the next line to enable Git repository updates.
# git_repos = true

# Uncomment and populate the list below with the full paths to your local Git repositories.
# git_repo_paths = [
#    "~/dotfiles",                # Example: Your dotfiles repository
#    "~/git/my-scripts",          # Example: A personal scripts repository
#    "~/Work/project-template",   # Example: A project template repository
# ]

# Optional: Use a different command instead of the default 'git pull'.
# git_commands = ["git pull --rebase --autostash"]


# --- Language/Package Managers ---
# Settings for specific package managers detected by Topgrade.
# Example: Disable checking global npm packages even if npm is installed.
# (Could also add "npm_global_packages" to the disable list above)
# npm_global_packages = false


# --- Pre/Post Hooks (Optional) ---
# Define custom commands to run before or after Topgrade's main steps.

# Example: Trigger Atuin sync explicitly (Optional, as Atuin usually syncs automatically)
# post_hooks = [
#    { command = "atuin", args = ["sync"] }
# ]


# --- General Configuration ---
# These settings control Topgrade's overall behavior.
# Note: Root-level boolean flags like confirm=true, cleanup=true caused parse errors.
# Topgrade likely uses sensible defaults for these or they are command-line flags.

# Example: Ask for confirmation before running potentially disruptive steps (Default behavior)
# confirm = true # This caused parse errors previously

# Example: Run cleanup steps automatically (Default behavior)
# cleanup = true # This caused parse errors previously

# Example: Prevent errors by disabling steps if tool is missing (Default behavior)
# disable_missing_tools = true # This caused parse errors previously

# Optional: Set the number of concurrent tasks Topgrade runs (default depends on CPU cores)
# max_concurrent_tasks = 4
