#!/usr/bin/env bash
# Write ~/.zshrc.local from Proton Pass login items (password / custom fields).
#
# Mapping is **gitignored** so this public repo never lists private Pass titles:
#   cp scripts/pass-env-map.example scripts/pass-env-map.local
#
# Format per line: Pass_title|ENV_VAR|field1[|field2|…]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=pass-map-lib.sh
source "$SCRIPT_DIR/pass-map-lib.sh"

VAULT="${PASS_VAULT:-Personal}"
MAP_FILE="${PASS_ENV_MAP:-$SCRIPT_DIR/pass-env-map.local}"
EXAMPLE="$SCRIPT_DIR/pass-env-map.example"
OUT="${ZSHRC_LOCAL_OUT:-$HOME/.zshrc.local}"

if ! command -v pass-cli >/dev/null 2>&1; then
  echo "ERROR: pass-cli not found" >&2
  exit 1
fi
if ! pass-cli vault list >/dev/null 2>&1; then
  echo "ERROR: pass-cli not logged in" >&2
  exit 1
fi

pass_map_require "$MAP_FILE" "$EXAMPLE" || exit 1
MAP=()
while IFS= read -r line; do
  MAP+=("$line")
done < <(pass_map_load_lines "$MAP_FILE")
[[ ${#MAP[@]} -gt 0 ]] || { echo "ERROR: empty map $MAP_FILE" >&2; exit 1; }

tmp=$(mktemp)
chmod 600 "$tmp"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by pass-write-zshrc-local.sh — do not commit"
  echo "# Regenerated: $(date -u +%Y-%m-%dT%H:%MZ)"
  echo
} >"$tmp"

written=0
for row in "${MAP[@]}"; do
  IFS='|' read -r title envvar f1 f2 f3 f4 <<<"$row"
  val=""
  used_field=""
  for field in "$f1" "$f2" "$f3" "$f4"; do
    [[ -z "$field" ]] && continue
    cand=$(pass-cli item view --vault-name "$VAULT" --item-title "$title" --field "$field" 2>/dev/null || true)
    if [[ -n "${cand// }" ]]; then
      val=$cand
      used_field=$field
      break
    fi
  done
  if [[ -z "${val// }" ]]; then
    echo "SKIP (empty/missing): $title → $envvar" >&2
    continue
  fi
  esc=${val//\'/\'\\\'\'}
  printf "export %s='%s'\n" "$envvar" "$esc" >>"$tmp"
  echo "OK $envvar ← field $used_field" >&2
  written=$((written + 1))
done

if [[ "$written" -eq 0 ]]; then
  echo "ERROR: no secrets written" >&2
  exit 1
fi

MARKER="# --- pass-write-zshrc-local managed above ---"
if [[ -f "$OUT" ]] && grep -q "$MARKER" "$OUT" 2>/dev/null; then
  {
    cat "$tmp"
    echo "$MARKER"
    sed -n "/$MARKER/,\$p" "$OUT" | tail -n +2
  } >"${tmp}.merged"
  mv "${tmp}.merged" "$tmp"
else
  echo "$MARKER" >>"$tmp"
  echo "# Add machine-only overrides below this line." >>"$tmp"
fi

cp "$tmp" "$OUT"
chmod 600 "$OUT"
echo "Wrote $OUT ($written exports)"
